### ISSUE TITLE
Can this plugin be scalled ?

### ISSUE THREAD

**Issue by kopax** [idangozlan/verdaccio-bitbucket#10]
Hi and thanks for making this module, we are wondering how does the `getCache` that use application memory to store the username/password can get scaled. 

- cache implementation: https://github.com/idangozlan/verdaccio-bitbucket/blob/master/src/cache.js 
- usage: https://github.com/idangozlan/verdaccio-bitbucket/blob/master/src/index.js#L92

Why didn't you choose a db service such as redis? What are the concerns if we are willing to scale verdaccio to multiples instances? Will the user have to login one time per instance ?

**Comment by idangozlan** [comment]
It will be great to add redis driver to this module, please PR it and I'll accept ASAP.

Thanks!

**Comment by kopax** [comment]
Hi, we are evaluating, so we need a proper answer. How is this working for you?

**Comment by idangozlan** [comment]
Yes. Please check version 2.0.0
