### ISSUE TITLE
Installation of v1.0.5 fails

### ISSUE THREAD

**Issue by yelworc** [idangozlan/verdaccio-bitbucket#17]
The package installation is failing with the following output for me:

```vagrant@uniq-stretch:~$ npm i -g verdaccio-bitbucket                                                                                10:36AM

> verdaccio-bitbucket@1.0.5 postinstall /home/vagrant/.nvm/versions/node/v10.15.0/lib/node_modules/verdaccio-bitbucket
> npm run build

> verdaccio-bitbucket@1.0.5 prebuild /home/vagrant/.nvm/versions/node/v10.15.0/lib/node_modules/verdaccio-bitbucket
> npm run clean:build

> verdaccio-bitbucket@1.0.5 clean:build /home/vagrant/.nvm/versions/node/v10.15.0/lib/node_modules/verdaccio-bitbucket
> rimraf ./lib

sh: 1: rimraf: not found
```

Apparently the `devDependencies`, which include rimraf, are not being installed (not sure if they should be). Installing v1.0.4 works fine; commit 7d7666f seems to have introduced the problem.

**Comment by yelworc** [comment]
Here's a full verbose output of the npm call: https://gist.github.com/yelworc/d845a7a1243b42af2baffa9c56ba211d

**Comment by oeph** [comment]
I think this can be closed, since we already have the working version 1.0.6
