### ISSUE TITLE
babel building to ES6

### ISSUE THREAD

**Issue by AceVentura** [idangozlan/verdaccio-bitbucket#18]
I found an issue related to the binary in npm registry. It's missing the .babelrc file. Because of that it's building in ES6 instead of ES5, which afterwards breaks nodejs. The temporary fix I made was placing the file in the verdaccio-bitbucket folder and run a new npm install.

**Comment by juanpicado** [comment]
@AceVentura I don't get the request. Could you clarify a little bit?

**Comment by juanpicado** [comment]
Ohh I see, that's bad. It's due https://github.com/idangozlan/verdaccio-bitbucket/commit/cb9a2dfb737118cf3e2516d281b8dfa4ef3b3e5b#diff-e56633f72ecc521128b3db6586074d2c
A PR would be on `.babelrc`

```
"presets": [
        ["@babel/env", {
          "targets": {
            "node": "6.10"
          }
        }]],
```
Which is the minimum version supported by Verdaccio.

**Comment by juanpicado** [comment]
@AceVentura if you PR I guess @idangozlan will be happy to merge and release.

**Comment by AceVentura** [comment]
I can do the PR no problem. The ".npmignore" file also needs to be changed, if I'm not mistaken

**Comment by raffaeleguidi** [comment]
...waiting for the update in npm :)

**Comment by juanpicado** [comment]
@AceVentura 
> Without the .babelrc the js files are compiled to ES6.

Why would you remove the ` .babelrc`. The project compiles perfectly to ES5 with the current setup.

**Comment by AceVentura** [comment]
@juanpicado I didn't. The npm binary doesn't have it (check the .npmignore)

**Comment by idangozlan** [comment]
Please check version 2.0.0
