### ISSUE TITLE
[Question]Bitbucket API changes (GDPR)

### ISSUE THREAD

**Issue by AceVentura** [idangozlan/verdaccio-bitbucket#21]
Is this change gonna affect anything on how the plugin is working now? 
https://developer.atlassian.com/cloud/bitbucket/bbc-gdpr-api-migration-guide/

**Comment by idangozlan** [comment]
I haven't tested the new api changes.

**Comment by claytonpiccinin** [comment]
@AceVentura did you tested it? Do you think it will be a problem? I'm in doubt about it too.

**Comment by idangozlan** [comment]
Seems like it works great.
