### ISSUE TITLE
How to share auth when more than one instance of verdaccio is running

### ISSUE THREAD

**Issue by abhinavdhasmana** [idangozlan/verdaccio-bitbucket#23]
Thank you for this awesome plugin!

To increase the reliability of the system, I wanted to run two docker instances of verdaccio with a load balancer in front. However, since the auth in managed in-memory, this does not work.

I have read the issue [Can this plugin be scaled ?](https://github.com/idangozlan/verdaccio-bitbucket/issues/10) as well.

So here are few questions:
* Is this possible in the current implementation?
* If not, I can try and work on redis implementation if some one can share some thoughts on its implementation.

**Comment by idangozlan** [comment]
Hi @abhinavdhasmana, I haven't tested it.
If you have some time to give it a try, it can be awesome :) share with us the results.

Thanks.

**Comment by idangozlan** [comment]
Hi @abhinavdhasmana , I will try to add Redis support and will post the result.

**Comment by idangozlan** [comment]
Please check version 2.0.0

**Comment by abhinavdhasmana** [comment]
Thanks a lot @idangozlan for such a fast turn around. Let me give this a try
