### ISSUE TITLE
Only admins in bitbucket team can be authenticated

### ISSUE THREAD

**Issue by ath88** [idangozlan/verdaccio-bitbucket#3]
From what I notice when using this plugin, the API endpoint 'https://api.bitbucket.org/1.0/user/privileges/' only returns the teams where the user is an admin. This effectively blocks only members of the team to log in using the plugin.

A solution could be to use Bitbuckets 2.0 API, like so:
https://api.bitbucket.org/2.0/teams?role=member

Documentation is here: https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams

**Comment by idangozlan** [comment]
You are more than welcome to create PR :) I don't have any extra time do
that..

Thanks!

**Comment by ath88** [comment]
Righto - on it.
