### ISSUE TITLE
adding to docker image

### ISSUE THREAD

**Issue by stephen-dahl** [idangozlan/verdaccio-bitbucket#30]
The verdaccio docker image uses alpine and there are no prebuild versions of your bcrypt dependency for alpine. This means that it had to build from source. I ended up with this dockerfile.

```
FROM verdaccio/verdaccio

USER root

ENV NODE_ENV=production

RUN apk add --no-cache --virtual .build-deps alpine-sdk python \
 && npm i --production verdaccio-bitbucket \
 && apk del .build-deps

USER verdaccio
```
should this be added to your docs? or maybe you publish an image with this already done?

**Comment by SamirMaina-districtm** [comment]
Perhaps use [bcryptjs](https://www.npmjs.com/package/bcryptjs) instead to avoid the python dependency altogether?

**Comment by stephen-dahl** [comment]
i was only using python during the build, it is not in my final image. still if your saying i can replace the word python with bcrypt in this script then that could be good.

**Comment by stephen-dahl** [comment]
nvm, I see that your saying to the devs replace their dependancy.
