### ISSUE TITLE
[Question] Bitbucket teams API endpoint deprecation

### ISSUE THREAD

**Issue by cone56** [idangozlan/verdaccio-bitbucket#35]
Hi,

Will the upcoming depreciation of the `/2.0/teams` and `/2.0/users` API endpoints affect this module?

> Change notice: Deprecating /2.0/teams/ and some /2.0/users API endpoints: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/

**Comment by betosales** [comment]
hello @cone56 , I opened a new PR #36 to fix this deprecation issue.

**Comment by betosales** [comment]
now you can close your issue, my PR #36 was approved dude.

**Comment by cone56** [comment]
Hey @betosales, thanks a lot for your work! Closing issue.
