### ISSUE TITLE
Bitbucket user roles do not match with documentation

### ISSUE THREAD

**Issue by ath88** [idangozlan/verdaccio-bitbucket#5]
It appears that the actual user roles in the Bitbucket API version 2.0 doesn't match with the expected roles in the documentation.

From https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams there appears to be 3 different roles:
- member
- admin
- contributor

The documentation for this plugin mentions:
- admin
- collaborator

I suggest that the plugin is altered to match the user roles from the Bitbucket API. Would that be prudent?

**Comment by asciimo** [comment]
It would be helpful to mention that you can see what privileges a user has by calling the API yourself: `curl --user you@your.org:password https://api.bitbucket.org/1.0/user/privileges` This was very helpful in my case, as the Bitbucket API was only showing me pretty versions of the real values.

**Comment by idangozlan** [comment]
Fixed on v2.0.0
