### ISSUE TITLE
Error 400 when I try to login

### ISSUE THREAD

**Issue by fabienc974** [idangozlan/verdaccio-bitbucket#9]
Dear, 
I've tried login with my bitbucket account, but I've never succeed.

I always have a 400 error, and I don't know what to do. 

I've asked on Stack, but no one  seems to face this issue.

Could you help me please ?
This the full log 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'https://fabienc974@bitbucket.org/fabienc974/lionjar-master' ]
2 info using npm@5.7.1
3 info using node@v8.9.3
4 verbose config Skipping project config: /Users/slizee/.npmrc. (matches userconfig)
5 verbose npm-session eb79804c963f0c18
6 verbose web login before first POST
7 http request → POST https://fabienc974@bitbucket.org/fabienc974/-/v1/login
8 http 400 ← Bad Request (https://fabienc974@bitbucket.org/fabienc974/-/v1/login)
9 verbose web login not supported, trying couch
10 verbose login before first PUT { _id: 'org.couchdb.user:fabien.clotilde..gmail.com',
10 verbose login   name: 'fabien.clotilde..gmail.com',
10 verbose login   password: 'XXXXX',
10 verbose login   type: 'user',
10 verbose login   roles: [],
10 verbose login   date: '2018-03-13T21:35:53.622Z' }
11 http request → PUT https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com
12 http 400 ← Bad Request (https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com)
13 verbose adduser before first PUT { _id: 'org.couchdb.user:fabien.clotilde..gmail.com',
13 verbose adduser   name: 'fabien.clotilde..gmail.com',
13 verbose adduser   password: 'XXXXX',
13 verbose adduser   email: 'fabien.clotilde@gmail.com',
13 verbose adduser   type: 'user',
13 verbose adduser   roles: [],
13 verbose adduser   date: '2018-03-13T21:35:54.309Z' }
14 http request → PUT https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com
15 http 400 ← Bad Request (https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com)
16 verbose stack Error: Registry returned 400 for PUT on https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com
16 verbose stack     at fetch.defaults.catch.then.then.result (/usr/local/lib/node_modules/npm/node_modules/npm-profile/index.js:376:13)
16 verbose stack     at <anonymous>
16 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
17 verbose statusCode 400
18 verbose pkgid org.couchdb.user:fabien.clotilde..gmail.com
19 verbose cwd /Users/slizee
20 verbose Darwin 17.3.0
21 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser" "--registry" "https://fabienc974@bitbucket.org/fabienc974/lionjar-master"
22 verbose node v8.9.3
23 verbose npm  v5.7.1
24 error code E400
25 error Registry returned 400 for PUT on https://fabienc974@bitbucket.org/fabienc974/-/user/org.couchdb.user:fabien.clotilde..gmail.com
26 verbose exit [ 1, true ]`

Thank for you help

Fabien

**Comment by juanpicado** [comment]
FYI https://stackoverflow.com/questions/49261954/verdaccio-bitbucket-error-400

**Comment by idangozlan** [comment]
Hi, should be fixed in v2.0.0, please test and tell us if you still experiencing the same issue.
